version: 2

models:
  - name: dim_zones
    description: >
      List of unique zones idefied by locationid. 
  - name: fact_trips
    description: >
      Taxi trips corresponding to service zones.
      The table contains records where both pickup and dropoff locations are valid and known zones. 
      Each record corresponds to a trip uniquely identified by tripid. 
      